<?PHP
/* Copyright Lime Technology LLC.
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 */
?>
<?php
include "plugins/webGui/include/app.php";

// MORE: put this in a webGui config file or just get rid of it?
//$defaultLayout = "classic_layout.php";
$defaultLayout = "default_layout.php";

// Suppose we want to render the page "http://tower/Main/Disk?name=disk1"
// emhttp calls 'popen(cmdline)' where cmdline is:

//  "cd /usr/local/emhttp; /usr/bin/php index.php name=disk1&path=Main/Disk"
//                                      argv[0]                  argv[1]

// The output of popen() (ie, the output generated by index.php) is written to
// the http socket (after http headers have been output).

// Parse the 'querystring'
// variables provided by emhttp:
//   path=<path>   page path, e.g., path=Main/Disk
//   prev=<path>   prev path, e.g., prev=Main (used to deterine if page was refreshed)
parse_str($argv[1]);

// The current "task" is the first element of the path
$task = strtok($path, "/");

// Read the webGui configuration preferences
$settings = parse_ini_file("/usr/local/emhttp/plugins/webGui/default_settings.ini", true);
if (is_file("/boot/config/plugins/webGui/webGui.cfg")) {
  $settings = array_merge($settings, parse_ini_file("/boot/config/plugins/webGui/webGui.cfg", true));
}
extract($settings);
unset($settings);

// Read emhttp status
$var = parse_ini_file("/var/local/emhttp/var.ini");
$sec = parse_ini_file("/var/local/emhttp/sec.ini", TRUE);
$devs = parse_ini_file("/var/local/emhttp/devs.ini", TRUE);
$disks = parse_ini_file("/var/local/emhttp/disks.ini", TRUE);
$users = parse_ini_file("/var/local/emhttp/users.ini", TRUE);
$shares = parse_ini_file("/var/local/emhttp/shares.ini", TRUE);
$sec_afp = parse_ini_file("/var/local/emhttp/sec_afp.ini", TRUE);
$sec_nfs = parse_ini_file("/var/local/emhttp/sec_nfs.ini", TRUE);

// Set our timezone
date_default_timezone_set($var['timeZone']);

// Build the webGui pages first, then plugin pages
$page_array = array();
build_pages("plugins/webGui/*.page");
foreach (glob("plugins/*", GLOB_NOSORT) as $plugin)
  if ($plugin != "plugins/webGui")
    build_pages("$plugin/*.page");

// Here's the page we're rendering
$myPage = $page_array[basename($path)];

// Gittyup
if (empty($myPage['Layout']))
  include "plugins/webGui/include/$defaultLayout";
else
  include "plugins/webGui/include/{$myPage['Layout']}";
?>
